import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  setup: [
    'setup/index',
    {
      type: 'category',
      label: '0. Before you start',
      collapsible: false,
      items: ['setup/project-settings', 'setup/project-decisions', 'setup/licenses', 'setup/local-environment', 'setup/identity-provider'],
    },
    {
      type: 'category',
      label: '1. Create the solution',
      collapsible: false,
      items: ['setup/repository', 'setup/empty-solution', 'setup/solution-files'],
    },
    {
      type: 'category',
      label: '2. Generate the layers',
      collapsible: false,
      items: ['setup/domain', 'setup/application', 'setup/infrastructure', 'setup/api', 'setup/worker', 'setup/tests'],
    },
    {
      type: 'category',
      label: '3. Run it locally',
      collapsible: false,
      items: ['setup/local-services', 'setup/run-locally', 'setup/commit'],
    },
    {
      type: 'category',
      label: '4. Get ready to go live',
      collapsible: false,
      items: ['setup/ci', 'setup/sit-services', 'setup/sit-vm', 'setup/sit-deploy', 'setup/prod-services', 'setup/prod-vm', 'setup/prod-deploy'],
    },
    {
      type: 'category',
      label: '5. Hand over to feature work',
      collapsible: false,
      items: ['setup/first-feature'],
    },
  ],
  reference: [
    'reference/index',
    {
      type: 'category',
      label: 'Part 1: Architecture specification',
      items: [{type: 'autogenerated', dirName: 'reference/spec'}],
    },
    {
      type: 'category',
      label: 'Part 2: Boilerplate code',
      items: [{type: 'autogenerated', dirName: 'reference/code'}],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [{type: 'autogenerated', dirName: 'reference/appendix'}],
    },
  ],
};

export default sidebars;
